name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'archlinux-yay-docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GA_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: archlinux-yay-docker 
          push: true
          tags: ghcr.io/wereii/archlinux-yay:latest
          cache-from: type=registry,ref=ghcr.io/wereii/archlinux-yay:latest
          cache-to: type=inline

